image: docker:19
services:
  - docker:dind

stages:
 - build
 - deploy

cache:
  paths:
    - node_modules/

build:
  only:
    - master
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE


deploy:
  stage: deploy
  only:
    - master
  script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "52.220.39.194"  >> ~/.ssh/known_hosts
    - echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - ssh ubuntu@52.220.39.194 "docker pull $CI_REGISTRY_IMAGE"
    - ssh ubuntu@52.220.39.194 "docker stop $(docker ps -aq)"
    - ssh ubuntu@52.220.39.194 "docker rm $(docker ps -aq)"
    - ssh ubuntu@52.220.39.194 "docker run -d --name cicd -p 80:80 $CI_REGISTRY_IMAGE"
